### ISSUE TITLE
Use Kedro for pipelining

### ISSUE THREAD

**Issue by lvijnck** [everycure-org/matrix-disease-list#14]
Let's make sure to move this into a Kedro pipeline (similar to how Marcello did it).

Happy to set up some time with you to get there.

**Comment by matentzn** [comment]
How do we deal with the fact we need a human in the loop?

pipeline -> PR -> clinician review -> update PR (with review confirmations) -> merge

**Comment by lvijnck** [comment]
Wouldn't that naturally be handled by the release process?

**Comment by matentzn** [comment]
Maybe I dont understand how kedro works with semi-automated processes;

This is the entire process:

1. git checkout main (git fetch / pull)
2. create branch
3. Run build script (currently a shell script which is run inside a docker container)
4. create a PR with all the files changed
5. Invite EC medical personnel to review
6. Add review metadata and make requested changes (manual work), commit to branch
7. Let QC pass (currently none)
8. Merge

Which part exactly should be modelled as a Kedro pipeline?

**Comment by piotrkan** [comment]
@lvijnck @pascalwhoop @matwasilewski 

We had a discussion with @matentzn on how to make disease list repo more kedro compliant. To put you up to speed and also get your perspective: 
- at the moment disease list is being built by 1) pulling a static docker container with many external dependencies 2) running makefile inside of this container (makefile involves running sparql queries, python scripts etc)
- the disease list repo works fine now however it is not adherent to our standards (e.g. not written within kedro framework). We definitely want it to be adherent to the matrix standards however we shouldn't do a total refactor 
- the consensus we reached together with @matentzn is to build a simple kedro pipeline based on the docker python library which is calling python functions when possible but also calling subprocesses to execute makefiles when needed (eg sparql queries). Essentially something like 

```python 
from kedro.pipeline import Pipeline, node
from .nodes import setup_odk_container, execute_sparql_query, process_disease_list

def create_pipeline(**kwargs) -> Pipeline:
    return Pipeline(
        [
            node(
                func=pull_odk_container, # pulls docker container
                inputs="params:odk",
                outputs="container_id",
                name="setup_odk_container",
            ),
            node(
                func=nodes.subprocess_sparql_query, # calls makefile via subprocess to execute sparql within the container
                inputs=["container_id", "params:sparql"],
                outputs="query_results", 
                name="execute_sparql_query",
            ),
            etc...
        ] 
    )
```
WDYT? happy to build scaffolding unless one of you want to take a lead on this

**Comment by matwasilewski** [comment]
Thanks @piotrkan.

To make sure I understand the problem:

TASK
We're building a list of diseases that are relevant for Matrix. Building this list required multiple queries to federated data sources (SPARQL queries, API queries downloading files, hardcoded files in the repo). We expect this set of scripts to be continuously modified, or for the data sources themselves - to be updated, necessitating regular runs of the pipeline.

OUTPUT
The coalesced disease list (as .csv or .parquet) will be produced as a local file, and should be submitted as a PR to this repo, reviewed, merged in, and tagged as release. This disease list will be used in our Kedro pipelines downstream (eg. the file itself will be retrieved from the repo by some dataset in Kedro in the main Matrix project).

PROBLEM
We want to migrate the disease list generation pipeline to Kedro, to add steps into the pipeline, and to standardise across our projects. We will use that pipeline to pull a docker container, and to run scripts inside of that container. However, this is for convenience rather than for necessity.

Am I understanding this correctly?

**Comment by piotrkan** [comment]
@matwasilewski I would say correct but @matentzn might have something to add on this

We want matrix-related repos to be compliant to our ways of working and engineering standards, hence we would like disease list to be implemented in kedro. But we should avoid complete refactor and re-building of the repo as it's already working well.

**Comment by matwasilewski** [comment]
Unless there is a specific pain point identified by @matentzn that transition to Kedro would remove, I wonder seriously doubt if we will get our ROI on this refactor (especially since we do receive many complaints about Kedro being difficult to work with from our partners). 

The only relevant output of this repository is a release-based dataset, and Kedro pipeline within this project will not be integrated with a pipeline from the main one.

**Comment by matentzn** [comment]
@matwasilewski so far the repo works and it is self contained - the kedro migration is only necessary if we believe in the following:

- we want to use the Kedro repo layout as a sort of cookie-cutter for all everycure code basis to increase maintainability and standardise qc
- we want to combine the disease list with other pipelines like "dynamic disease tagging" which @piotrkan is working on; there are some arguments made by him and @lvijnck that the tags should be considered part of the disease list product and be shipped alongside it

I don't feel strongly either way! I will follow the Every Cure lead on this as you have a better understanding of the overarching strategy!
